spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: 1117
    username: postgres
    url: jdbc:postgresql://localhost:5432/o2021
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: o2021