# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container: azul/zulu-openjdk:11
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build Spring Boot
      run: |
          chmod +x mvnw 
          ./mvnw -B package
    - name: Subir reports de surefire
      uses: actions/upload-artifact@v2
      with:
        name: surefire-report
        path: target/surefire-reports/* 