# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ core ]
  pull_request:
    branches: [ core ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES-PASSWORD: 1117
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_DB: o2021

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Subir informes de surefire
      uses: actions/upload-artifact@v2
      with:
        name: surefire-report
        path: target/surefire-reports/*
    - name: Subir informes de cobertura
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: target/site/jacoco/* 